# MySolution(init)_231022
# import random
# N = int(input('정수를 입력하세요:'))
# M = random.randint(2*N+1, 1000000)
# PN = 'IOI'  
# for _ in range(1,N): PN+="OI"
# S = 'I'
# for _ in range(M):
#     S+=random.choice(['I','O'])
# print(N); print(M)

# 위의 random 값 생성하는데 상당히 오래 걸려서 테스트를 위해 임의의 값을 지정하여 제공함
PN = 'IOIOIOIOIOIO'
S = 'IIOIIIIIOOIIIIIOIIIIIOIOIOIIIIOIIOIIOOOOOIIIIOOOIOOOIOIOOOOOIOIOIIIOIOOOOIOOOIOIOOIIIOOIOIIIOOIOIIOIIIIOIOOOIIIOOIOOIOIIIIOOOIOIOOOIIIIIIIIIIOIIIOOIOIOIIIOOOIOIOIOIOIOIOIOIOIOIOIOIOIIOIIIOOIIOIOOOOIIOIOOIIIOIIOIOIIOIOOIIOOOIIIOOIIOOOIOOIOOOIIIOOIOOOOIOIIOIOIIOIOIOIIOOOOIOIOOIIOOOIOIOIIOIOIIIIOOIOIOOIOIIOIIIOIOOOOIOOOOOOIOIIOIIIOOOOOOIOOIOIOOIIIIOOOIIIOOIIIIOOIIIIOOOIOIIOIOIOIIOOOOIIOIOIIIIIIIIIIIOIOOOOOOOIOIIIOOIIOIIOIIIIOIIOIOOOOIIOIOOOOOIOIIIOIIOIOIOIOIOIIOOIOOIOOIOIIIOOOIIOIIIOIIOIIIOOOOIOIOIOOOOIOOOIIOIOIOIOIOIOIIOIOOOIIIIIOIIIOOOIIOIOIIIOIIIOOIOOOOOOIIIIIOOIIOIOOOOOOOIOIOIOOIIOIOIOOOIIOIIOIIOIOIOIOIOIOIIIIIOIIIIIOOIOIOIIOOOIOIOIOIOIOIOIOIOOOOOOIOOOOOOIOIIOIOOOIIOOIIIOIOOIOOOOOOOOOIIOOOOIOOOOOIOOOOIOIOIOIOIIIOIOIIOIOIIOOIOOOIIOOIIIOOOIOIOOIIOIOIOIOIOIOOIIOOIIIOIIOOOIIIOOOOIIIIIOOIIOOIIOOOIIOIIIOOIOIOIOOIOIIOIIIOIOOIIIIOOOOIIIIOIIOOOIOOOOOIOIIIIIIOIIOOOOOOIOIIIOIIIOOIOIOOIIOOIIIOIOOOIOIOOOIIOOOOIOIIOIOOOIOOIOOIOIOOIIIIOOOIOIOOIIOIIOOIOOOOOOOIIIOIIIIOIOOIOIIOIIOIIIIIIOIIIIIIIIOOIOIOOOIOIIOIOIOOIIIIIIOOIOOIIOOIIIOOOIOOIIOOOOOOOOOIIIIIIOOIOIIOIOOOOOIIOOIIIOIIIOIOOIOOIOOIOOOOIIIOIOOOIIIIOOOOIIOIIIIOIOIOIIIOOOIIIOOIIOOOIIIIOIIIIIOIOOIIOOOIOIOOOIIOIOOOOIOIIIIIOOIIIOOIOIOOIIOIOIOIOIOIOIOOIIIOOOIOOOOOIIOIOOOIOIOOIIOOIOOIIIIOOOIIIOOOOIIOIOOOIOIOIIOOOOIOOOOIIIOOIIOOIIOIIIIIOIOIOOIOOOOOIOOIIIOOOOOOOOOOOOOIOIOIOIOIOIIOIOOOOIOOIOIOOOIIIIOOIIIOIIOIIOIOIIIIOIOOOOOOOOOIIOOIIOOIOOIIIIOIOIOOOOIIOOIIIOIIOOIOOIOOIIIIOOOOIIOIOOOIIIOOOOOOIOIOOOOOIOIOIIIOIOIOIOIIIOOIOIOIIOIIOOIOIIOIOIIIIOIOIIIIOOIIIOIOIIOIIIIOOIOIOIOIIIOOIIIOOIIOIIIOIOIIOIOIIOIIIIIOOOIOOIIOOOOIOOOIIOIIOOOIOOOIOIOIOOIIIIOIIOIIOIOOIIOOIOOOIOIOIOIOIOIOOOOOIOOIIIIIOIOOIOOOOOOOIIIOIIIIIIOOOOIIOIOIIOIOOIIOOIIIOIIOOIIOOOIIOOOIIOOIOIOIIOIOIIOIIOIIIOIIOOOOOOIOIOOIOOIOIOOIOIOIOIOOIOIOIIIIIIIIIIOOIOIOIOIOIOIIOOIOOIIIIOOOIIIOOIIOIOIOOOIOOIOIIIOOIIIOOOOOOIIIOOOIIOOOOOIOOIIIIIOOOIOIIOOIOOIOOIOOIOIOOOIOIOIOIOIIOIOOOOIIOOOIOOIIIIOIOOOOOOOIIIIOIIIIIIIIIOIOIOIOIOIIOIIOIOIIIIIIOIIOOOOIIOIOOIOIOOIOOOOIIOOOOOOIOOIOIOOIIOOOOOOOOIOIOOIOIIOOIIOOIOOOOOOIIOOIOIOIIOIOIOIOOOOOIIIOOIIOIIOOOIOIIIOIIIIOIOOOOIIOIIIIIOIOIOIOIOIIOIOIOIOIOIOOOOIOIOIIIIOIIOIOOIOIOIOIIIOIOOOIOIOOOOIIOOOOOOOOIOIIIOOIIOOIIOOIOOIOIOIOIOOIOIOIIIIOIIIIIIOIOOOIIIIOIIIOOOIIOOIOOIIOIIOIOIOOOOOIOIOIIOOIIIOIIIIIOIIOOIIOOOOIIOIOOIOIOOIIOOIOOOOOIOOOIOIIIIOOOIIOOOOOOOOOOIOOOOOIOIIOIOOOIIOOOOOIIOOIOOIOOIIOOOIOOOIIOIIIOIIIOOIOOIIIIIOIOIOIOIOIOIIIIIIOOOOIIIOIOIIIOOOIOIIIIIOIIOOIIOOIIOOIOOOOOOOOIOIIIOOOIOOIOOOOOOOIIIOIIOOOIIIOIOIOIOIOIOIOOOOIIIIIOOOIIIIOOIIOIOIOIOIOIOOIIOOOOOIIIOOOIOIIOIOIIIIOOIIOIIIOIIIIIOIOIOIOIIOOIOIOOOOIOOIIIOOIOOIIOIIOIIIIOOOOIOOOIOOIIOOOIOOIOOOIIOIOIOIOIOIOIOOIOIOOOIIOIOIOIOIIIIIOOOIIOOIIOOOIOOIIIOOOIIIOIOOOOOOIOIOOOIOIIOOOIIOOOOOIOIIOIIOOIIOOOOOIOOIIOOOIOOOOIOOOOIIOIOIIIOIOIIOIOOOOIIOOIOOIIOOOIOIOOOIIIIIOIIIOOIOIOIOIIIOIOIOIOOOIIOIOOOOIOIOIOOOIOIOOOOOIIIOIIOOOIOIOOIOIOIIOIIOIIOIOIOIIOIOIIIIIIOIOOOOIOOIIIOOIOOOOOOOOIIOOOOOIIOIIOIOIOIOOIOOOOOOIOIOIOIIOIIOOOOOOIIIOIOOOIOOIOIOIOIOIOIOIIIOIOOIIOOIIOIOIIIOOIOIIOIIIOIIOOIOIOIIIOOIOIOIIIOIOOIIIOOIIIIIIIOOOIOOIOIIIIOOIIIOOIIOOIIOOIIIOIOOIOIIOOIIOIIOIIIIIOIIIOIOIIIOIOOIOIIIIIOIOOIIIOOOOIOOOIOIIIOOIOIOOIIIIOIIOIOOOOOOIIIOOIIOIIOIOIOIOOIIOOOIOIOIOOIIIOOIIIIOOIOIIOOIIIIIOIOIOOIIIOIIOOIIOOOIIIIOOIIOIOIIOOOIOIOIIOIOOIIOIOIOIIIIOOIIOOIOOIIOIIOIIOOIOOOIIIOIIIIOOIOIIIIIOIOOOOIOIOIIOIOOOIIOOOIIIIIOIOIIIIOOIIIOIOIOIOIOIOIOIIOOOOIIOOIOIIIOOIIOIOOIOIIOIOOOOOOOOOOIIIOIOOOIOIOOIOOIOIOIIOIIIOOOIIIOOOOIIIIOOOIIIIIOIOOIIIIOOIIOOIIOOIOOOIOOIIIIOIOOOIIOOIIIOOIOOIOOIIOIOIOOIOIOIOOIOIOOOOOOOOOIOIIIOOIIIIIOOOIOIOIOOIIIIIOIOIOOOOIOOOIIOIOOOOIOIIIIIIIIIIOOIIOOOOIOOIOIOIOIOOOIOIOOIOOOOIOOOIOIIIOIOIOOIOIIOOOIIIOIIIOOIIOOOOOOOIIIOOOIIOOIOOOIOIIOIOIIOIOIIOIOOOIIOIIIOIIIOOIOIIOOIIIOIIIIIIIOOOIIOIOOOIOIIOIIIOOIOOOIIOIOIIOIIIOIIOOIOIIIOIIOIOIOOOOIOOOIOIIOOOIIOOIOIOOIIOOIIOOOIIOOIIOIIOIIOOIIOIOIOIOIOIOIOIIIOOIIOIIOOOOIIOOOOOIIIOOIOIOIIIOOOOOOIIIIIOOOOOOIIIOOOIIIOOOOIOIOOOIOIIOOOIIIIIOOOOOIIOOIOOIIIOIOOIIOIIIIOOOOIOIIOIOIOOOIIOIOIOIOIOIOOOOOIOIOIOOIIIOIIOOIOOIIOOOOIOIIOIOOOIIOOOIIOOIIIOOIOOOOIIIOOOOIOIIOIIIOIIIOIIIIIOOIIIOIIIOIOIIIOIIOIIOIOIOOIOOIIIOIOIIOIOIOOOOOIIIOOIOOOIIOIOOOOOIOOIOIIIOOOOIOOOOOIIIIOOIOIIIOOOIOOIIIIOOOOOIOOIIIIIIIIIOIIOOOIIOOIIOOIIOOIOOOOOOIIIIIOIOOOIOIIIOIOOOOOIOIOIIOIOIOIOOIIIIOOOIIIIIIOIOIOIIIIOIIOIIIIIIOOIIOOIIOIOIIIOOIIOIOIIIOOOIOOIIIIIIIOIIIOOOIIOOIOIOIIIOIIOOIIIIIIOIOIOIOOIOIOOOOIOOIOIIOIIIIIOIIIOOOIIOOOIIIOIOIOIOIIOOOIOIIOIOOIIOIIOIOOIOIOOIIOOOIIIIOIOOOIOOOOIOIOIOIIIIOIOOIIOIIIIIOOOOOIOOIIIIIOIOIOOOIIOIIOIIOOIOIIIIIOOIIIOOIOOOOOIOOOOIIOIOOIOIOIOOIIOOOOIOIOOIOOOIIOOIIIOIIOIOOOOOIIIOIIOIIIOOIOOIOOOIIOOIIOIIIOIIIOOOOIIIIIOIOOOIOIOIIIOOOIOIIOIOIOIOIOOOIIOIIOOIOOOOIOIOOIOIOIOIOIOOIOIIIIIIIOIIOIIIOIOIIIIOOOIOIOIOIOIOIIOIOIOOIIIIOOOOIOIIIIOIIOIIOOOOOOIIIIIOOIOIIOIOIIIIOIIIOOIOIOOIIOIIIOOOIOOOOIIOIOOOOOOOOOOOOOOIIIOIIOOOIIOOOOIIOOIOIOIOIOOIIOOOOIOIIOIIIOIOIIOIOIOIOIIIIIOIOOOOOOOOIIIIIIIOOOOOOIIIIIIOOOOIOOOIOIOIOIOIOOIOIIOOOIIOIOOOOOOIIIIOOIOIIOOIIOIIIIOOOOOIOIIIIIOOOOIIIOOIIIIOIIOOOIOIIIOIOIIIOIIIOIIIIIIIOOOIOIIIOIIIIOIOIOIOIIIOIOOOIOOOIOOIIIIIOIOOIOIIIOIIOOOIIIIIIIIOOIIOOIOOIIIOIOOIIIOIOOOOOIIOIOOOIOIIOOOIOIOOOIIOIOIIOOOOIIOIOIIIOIOOOOOOOOOIIOOOOIIIIOIOIIOIIOOIOIIOIIIOOOIIIIIIIOIOOIIOOOOOIIIIOIOIIOOIIOOIOOOIOOOOIIOOIOIOOIOOIOOOIIIIIOIIIOIIOIOOOOIIOOOOIIOIIOOOIIIIOIIIIIIIOIIOOIIIIIIOOOIOOOIOIOOIIIOOIIIOOIIIOOIIOIOOIIIOOIOIOIOIOOIOIIOIIIIOOIIOIIOOIOOIIOOIOIIOIOOOOOIOOOOOIOOIIOIOIOOOIOIOIIIOIIIIOIIOIIIIIOOIOOIOIOOIOOOOOIIOIOIIIOOOIOIIOOIIIIIOIIOIIOIOIOOIOOOOOOOOOIIOOIOOIIOOOOOOOIOOOOOIIOIOIIOOOOOIIIOOOOIOOOIOOIOIOOOOOIIIOIIOOIOIOOIOIIOIIIIIOIOOIOIIIOOOOOOIOOOOIOOOOIIOIIOOIIOIOOIIOIOOIIIOOIOIOIOIOOIIOIIIIIOIOIIIOOIIOOIIOOOOIIIIIOOOOOOOIOIOOIOIIIIIOIIOIIOIIIOOIOOOIIOOOOIOOIIOOIIIIIOOIOIOIOIOIOIOOOOIIOOIOIIOOOOIIIIOIOOIOOOIOOIOIIIIIIOOIIOOOOOIOOIIOOOIOIIIIOIIIIIOIOOIOIIIIIOIIOOIOOIOOIOOOIIOOOIOOIOIIOIIIIOIOOOOIOOIIOOIOOIIOOOIIIOOIOOOIOOIIOIIIIOOOIOOOIOOOIOOOOOOIIIOOOOOIOOIOOOOIOIIIIIOOOOOOIOIOOIOIIIOOIIOOIOOOIIOOIOIIIOOOOOIOIOOOOIOOOOOIOOIOOIIIOOOOOOOIOOIIOOOIIOOIIIIIIOOOOOIOOOIIOIIIIOOOIIOIIIIIIOIOIIIOOOOIIOIIIOOOOIIOOOIIOIOOOOOOIIOOOOOOOOIIIIIOOIOOOIOIOOIIIOIIOIIOIOOOIIIIIOOIOOIOIOIIIOOOIIIOOIIOIOIIIOIIOOOIIOIOOIOIIIOOOOIOIOIOIOIIOIIOIOOOIIOIIIOIIOOOOIOIIOIIOIOIOIIOOOIOOIIIOOIOOIOIOOIOIOIOOIIIOIIOIOOIIIIOIOIOIOIOOIIOIIOIIIIIIOOIIIOIOIOOIIIOOOIIIOIIIIOOIOOOOOOOIIIOIOIIOOIOOOIOOIOOIOOIOOIIOIIOOOOOOIIIOOOOOIOOIOIOIIIIIOOOIOOOIOOOIOIIIIOOOOOOIOIOOIIIOOIOOOIIOOIIIOOOOOIOIOIIOIIOOIIIIOIOOIIIIOOIIOIOIIOOIIIIOIOIIOOIIIOOOIIOOIIOIIIIOOOIIIOOOIIIIIIOOOOOOIOIIIIOOIIOOOOOOIIOOIOIOIOIOIOIOOOIIIOOIOIOOOIOOOOIOIIOIOIOIIIIOOOOIIIOOOIIIOOOIIIIOIOIIOIIIIIOIOOIIIOIOOOIOIOIOIIIIIIOOOOIOOOIIOOIIOOIIOOOIIIIOOIIOIIOIIOIIIIIIOIIIOOOOOOIIIIOIOIOOOIIOIIIOIIIIIOIOOOIOOOOIIIIOOIIOIOOOOIOOOIIOIIOIIIIOIOOOIOOOIIOOIIIIIOOOOOOIIIIOOOOIIOIIIIOIOIIIOOIOIOOOIOOOOIIOIOIIOOIOIIOIIOIOIOOIIOIIIOIOIOOIIOIOOOIOOIIIIIIOIOIIIIIOIOOOIIOIOIOIOIOIOOIOOOIIOIOOIIOIIOOIIOOIIIOOOIOIOOOIIOOIOOIOIOIIOOOIOIIOOOIOIIIIIIOIIOIIOOOIIOIOIIIOOOIOIOOIOIIOOOOOIOIIOIOIIIOIOOIIIOOIOOIIIIIOOIOIIIOOOIIIIOIOIOIOIOIOOOIOOIOOOIIOIOIIIIIIOIOOIIIIIOOOIOIIOIOIIIIOIOIOIIIIOOOIIIIIOIOIIOIIOOOOOIIIOIOIOIIOIOOOIIOOOOIIOOOOIIIIOIOOIOOOOOIIIOIOIOIOOIIIIIOIOOOOOIOOIIOOIOIOIOOIOOIOOOIIOIOOIOIIOIOIIOOIIIOIOOOIIOIOIOIIOIOIIIIIOOIOIOOOOOOIOIIIOIOIOOIOIOIIIIOOIIIOOOOIIOIOIIOOOOIIOIOOOIIIIOOOIOIIOIIIIIIOOOIIOIIIOOIIIOIOOOOOOOOOOIOOOOOOIOOIIOIIIIIIIIOIOOIOIOIOIOOOIOIOOIOIIIIIIIIIIIIIOOIIIIIOIOOOOIOOIOOOIIIOOIOOIIIIOOOIIIIIOIOIIIIIOOIIOIOOIIOIOIIOIOOOOOOOOIIOOOOOOOIOOOOOOIOOOIIOOOOOIIOOOIIIIIIOIOIOIOOIIOOIOIOIOOOOOIOIIIIIIOOIIIIOOOOIIOIIOOIIIIOOOIOOOOOIOOIIOOOIIIIOOIOOOIOIOIOIIOOIOIIIIOIOOIOOIOOOOOIIIIIOOIIOIIIOIIOOOIOIIIOIOOIIOOIOIOOIOIIIOIIIOIOOOOIOOIOOOIOIOIOOIOIOIOIIIIOOOOOOIOOIIIIIOOIOOOOOIIIOIOOIOOOIIOIOIIIIIOIOOOIOIIOIIOOOOIIOOIOIIIOOOOOIIOOOOOIIOIIIOOIIOIOOIOIIOIOIIIOIIOIOIIOOIOOIIOIOIOIIOIIOIOIOOOIOIOIIIIIOOIOOIIIIOOIOOIIOOOIOIOIIIIIOIIOIIIIOIIIOIOIOIOOOOIIOOOOIIIOIIOIOIIOOIIOIIIIIIIOIIOIOIIOIIIOIIIOIOOOOOIIOOIIOIOIOIIOIOOIIOOOIIIOIOOOIOOIIOIOOOOIOIOOIIIIIIOOOIIIIIIIOOOIOIOOOOOIOIIIIOIOOIOIOIIIIIIIOOOOOIIIOOOIOOIOIOOIOIIIOOIIIOOIIIIOOOIIOIIOOIOIOIIOIIIOIIIIOOOIOIIIIIOOOOIOIOIIOIIIIIIOOIIIIIIOIIIIOIOIIOIIOIIOIOOOOIIOOIIIIIIOOIIOIIOIIIOIOOIIIIIOIIIIIIOOOOIIIIIIIOIIIOIIIIOIOIIIIIIOOIOIOIOIOIOOOIIIIOIOIIIOIIIOIIIIOOIOOOOIOIOIIOOIIIOOIIOOOOOOIIOIIIOIOIIOOOIIOIIIOOOOOOIOOIIOIIIOIOIOIIIIIOOOIOIIOIOOOOIOOIOOIIIOIOOOIOOOIIIIIIOIOOOOOOIIOIIIOOIIIOIIOIIIOIOOIIIIOOOIOIIIOOIIOIIOOIIIIIIOOIOOOIOOIOOIIOIOIOIOIOIOIIIOIIOOOOIIIIOOOIIOOOIIOIIIOIOIIIOIOOIIIOOIIOIOIIOIOIIOIIOIOIIOOIIOOIOOIOOIOOOOOOIOIIOIOIOIOIOIOIOIIIIIOOOIOOOOOIOIOIOIOIOIOOIOIIOOIIIIOOOOOOOOOOIOOOIIIIOOOIOOIIOOIOOOOOIIOIIOOIOOIIIIOOIIIOIOOIOOIOOOIIIIOIOOOIIIIOIOIOIIOIOIIOOIIIOIOOIOOOOIOIIOIIOOOIIIIIOOIIOOIIOOOIOOIOIOIOIIOIOIOIOOIOOIIOOOIOIIIIOOIIIOIIIIOIOIIOOIIIIIIOIOOIIIIOIIOIIOIIIIIOOIIIIOOIOOOIOIIOOOOIOIIOIOOIOIIOOIOOOOOIIOIIOIOIIIOOOIIIOIIOOOIOOOIIIIOOOOIOOIIOOIOIIOIOIOIIIOIOIOIIOIOIIOIIOOOOOIIOIIOOIOOIIOIIIOIOIIOIOOOOOOIIIOOIOIOOIIOIIIOIIIOOOIOOIIIIIOIIOIOIIOIIIOOIOIIIIOOOIOOIOOIIIIOIIOOIOOIIOIOOOOOIOIIIOIOIOOIIOIIOIIIOIIIOOOOIOIIOOOIIOIOOIIIOIOOIOIIIOIOIOIOOIOIIIIIOIIIOIIOIIIOOOIOIIOIIOIIIIOIIIOIOOOOIOOIIIOIOOOIIIIOIOOIOIIOIIIOOIOIOOOOIOOOOIIOOOIIOIIOIIOIOOOIOIOOIIIIIIIOIIOIIIOOOIOOIOIIIOOIOOOIOIOOIOIOOIIIIIIOOOOOIOIIOIOIOOOOIIIOOIOIIIOOIIIIIOOOIOOOOOIIIIIIOOIOOIOOIIIOIOIOIOIOIOIOOOIOOIIOIOIIIIIIIOOIOIOOIIIOOIIIIIIOOIOOIIOOOOIOIOOIIIIOIIIOIOIOIIOOOIIOIOOIOOIIOIOIIOOOIIIIOOOIIOOIOIIIIOIIOIOOOIIOIIIOIOIIOOOIOOIOIOOIIIOIIOIIOIOIIIOOIOOOOOIOIOIIIOIIIIIOOIIIIIOIIIOOOIOIIOOOOOIIIOOOOIIIIIIOOIIIOOIIIIIOOIIOIIIOIIIIIOIOOIOIIIIIIIIIIIOIIIOOOIOOOOIIIIOIIOIOOIOOIIIOOOIIOIOIOIOIOIOIOIIOIIIOIOOIIOOOIIOIOIOIIOIIOIOOIOIIIOIIOOOOOOOIOIIOOOOIOIIOOIOOOOOOIIIIOIIOIIOIOOIIIOIIOOOOOOOOIOIOIOIOIIOIOOOOOIOIIOOIIIOIIOOIOOOIOOIOOIOOOIIIIIIIOOOOOIOOIIIOOOOIIOOOIOIIIIIIIOIIIOOIOIIIIOIOIOOIOIOIOIOIIOIOIIOOOIIOIOOOIOIIIOIIOOOIOOOIOOOOOIOIIIOOIIOIOOIIIOOOOOOOIIOOIIOOIIIOOIIOIOIIIIIIIIOOOIOIOIIIIIOIIIIIIOIIOOOOIOOOIOOOOIIIOIOIOIIIOOOOOOIIOIIIIIOOOOOIIOOIOIOOOOIIIOIOIIIOOIIIIOOOIIIIOIOOOIOOOIIOIIOOOOIIIIIOOIIIIOOOOOOOIOIOIOIOIOIOOOOOOOOOOOOIOIOOOIOOOIOIOIIIIIOIIOOOIOIIIIOOIOIOIOOIOIIOIOIOIOOIOIOIIIIOIIOOOOOIIIOOOIOIOOIOOIOOOOIOIOIIIIIIOOOOIOIIIIIOOIIIOIIIOOOOOOIOOIIOOIOIOIOIOIOIOOOOIIIOIIOIOOOIIIOIOIIOOOOIOOIIIOOOIIOIOIOOIOOIOIIIOOOOIOOOIOOIOOIIIIIOOIIOIIIOIOIIIIOIIIIOOOIIOIOIOIOIOIIIOOOIIIOIOIOOIIIIIIOIIIIOOOOIOOOOIOIOIOOOOIIOOIOIOIOIOOIOOIOIOOIIIIIOIOOIIIIOIIIIOOOOOIIOIOOOOIIIIOOIOIOOOOOIIIIOOIOIIOIIIIOIIOIOOOOIIOOIIIIIOIOIOOOOOOOIOOOOIOOIIOIIOIOIOIOIOIOIOIIIOOOIIOIIOOIOOIIIIIOIIOOIOOIOIOIOIOIOOIIIOIIOOOOIOOIOIIOOIIIOOOIIIIOIOOOIIIIOIIOOOIOIIIOIIOOOOIIIIOIIOOIIIOOIIOIOIOOOIOOIIOIOOOOOIOIIIIIIIOIOIOIOIOIOIOIOIOIOIOIOIOOIOIOIOIOIOIOIOIOIIOIOIOI'

def DonnySolution(S, PN):
    cnt = 0
    tmp = []
    for i in range(len(S)-len(PN)):
        if S[i] == 'I':
            tmp.append(S[i:i+len(PN)])
    for j in range(len(tmp)):
        if PN == tmp[j]: cnt += 1
    return cnt   # fin.

'''
 (GPT의 코드 리뷰)
 이 코드는 S의 길이가 매우 큰 경우에는 시간이 오래 걸릴 수 있습니다. 이를 개선하기 위해서는, KMP(Knuth-Morris-Pratt) 알고리즘을 사용할 수 있습니다. KMP 알고리즘은 문자열 검색 문제에서 시간 복잡도를 줄이기 위해 여러 알고리즘이 개발되었는데, 특히 S와 PN과 같은 두 문자열에서 하나의 문자열이 다른 문자열 내에 몇 번 나타나는지 찾는 문제에서는 가장 효과적입니다. 이 알고리즘의 핵심 포인트는, '겹치는 부분을 활용하여 시간 복잡도’를 줄이는 것에 있습니다. 이를 사용하면, S에서 PN이 몇 번 등장하는지를 더욱 효율적으로 구할 수 있습니다.
'''
# GPT가 추천하는 KMP 알고리즘 적용_240111
'''
이 코드에서는 computeLPS 함수를 이용하여 PN의 LPS(Longest proper prefix which is suffix) 배열을 구합니다. 이후, kmp_search 함수에서는 S를 순회하면서 PN이 몇 번 등장하는지를 구합니다. 이 때, PN의 LPS 배열을 이용하여 중복 탐색을 피합니다.
'''
def computeLPS(pat):
    lps = [0] * len(pat)
    leng = 0
    i = 1
    while i < len(pat):
        if pat[i] == pat[leng]:
            leng += 1
            lps[i] = leng
            i += 1
        else:
            if leng != 0:
                leng = lps[leng-1]
            else:
                lps[i] = 0
                i += 1
    return lps

def kmp_search(S, PN):
    cnt = 0
    lps = computeLPS(PN)
    i = j = 0
    while i < len(S):
        if S[i] == PN[j]:
            i += 1
            j += 1
        if j == len(PN):
            cnt += 1
            j = lps[j-1]
        elif i < len(S) and PN[j] != S[i]:
            if j != 0:
                j = lps[j-1]
            else:
                i += 1
    return cnt

'''
아래는 GPT에게 문제만 제공하고 풀이를 요청한 모범 답안들
'''
# GPT 생성 모범 답안1
# 이상함.. 제공한 문제에서 비교해야 할 값인 PN이 없다..
def solution(S):
    N = len(S)
    if N % 2 == 1:
        return False
    if S[0] != "I":
        return False
    for i in range(1, N, 2):
        if S[i] != "I":
            return False
    return True

# # GPT 생성 모범 답안2
# 이상함.. 제공한 문제에서 비교해야 할 값인 PN이 없다..
# def solution(S):
#     N = len(S)
#     cnt = 0
#     for i in range(N):
#         if S[i] == "I":
#             cnt += 1
#         else:
#             cnt -= 1
#     return cnt == 0


print('내 풀이:',DonnySolution(S,PN))
print('GPT 코드 수정:',kmp_search(S, PN))
print('GPT 생성 모범 답안:',solution(S))
