library(sqldf)
library(googleVis)
sqldf("SELECT * FROM Fruits")
sqldf("SELECT * FROM Fruits WHERE Fruit=\'Oranges\'")
sqldf("SELECT * FROM Fruits limit 5")
sqldf("SELECT * FROM Fruits ORDER BY Sales")
sqldf("SELECT * FROM Fruits ORDER BY Sales DESC")
sqldf("SELECT SUM(Sales) FROM Fruits")
sqldf("SELECT SUM(Sales), AVG(Sales), COUNT(Sales), MAX(Sales), MIN(Sales) FROM Fruits")
sqldf("SELECT Fruit, COUNT(Sales) FROM Fruits GROUP BY Fruit")
sqldf("SELECT * FROM Fruits WHERE Sales > (SELECT Sales FROM Fruits WHERE expenses=80)")
sqldf("SELECT * FROM Fruits WHERE Sales IN (SELECT Sales FROM Fruits WHERE expenses=80)")
sqldf(c('UPDATE Fruits SET Profit=20 WHERE Fruit=\'Oranges\' AND Year=2009', 'SELECT * FROM Fruits'))
sqldf(c('DELETE FROM Fruits WHERE Fruit=\'Oranges\' AND Year=2009', 'SELECT * FROM Fruits'))

# 실습하기
sqldf("SELECT * FROM Fruits limit 7")
sqldf("SELECT * FROM Fruits ORDER BY Expenses DESC")
sqldf("SELECT Fruit, AVG(Sales) FROM Fruits GROUP BY Fruit")
